apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: "products"
  version: "default"
  rules:
    - name: select_products_rule
      actions: ["select"]
      roles:
        - user
        - admin
      effect: EFFECT_ALLOW

    - name: create_update_delete_products_rule
      actions: ["create", "update", "delete"]
      roles:
        - admin
      effect: EFFECT_ALLOW

