services:
  zitadel:
    container_name: zitadel
    image: ghcr.io/zitadel/zitadel:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./auth/.env
    command: start-from-init --tlsMode disabled --masterkeyFromEnv
    depends_on:
      postgres:
        condition: "service_healthy"

  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:latest
    restart: unless-stopped
    ports:
      - "3592:3592"
    env_file:
      - ./auth/.env
    volumes:
      - ./cerbos:/policies
  backend:
    container_name: backend
    build: ../..
    ports:
      - "8081:8081"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ../../:/app
    env_file:
      - ./backend/.env
    environment:
      # override because of drizzle commands on host machine
      - DB_URL=postgresql://postgres:admin@postgres:5432/zitadel
    depends_on:
      postgres:
        condition: "service_healthy"
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    env_file:
      - ./auth/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
